#!/usr/bin/env Rscript
# Wrapper script for {TOOL_NAME} GenePattern module
# {TOOL_DESCRIPTION}
#
# Generated by GenePattern Module Toolkit

# Load required libraries with error checking
required_packages <- c("optparse"{REQUIRED_PACKAGES})
for (pkg in required_packages) {{
  if (!require(pkg, character.only = TRUE, quietly = TRUE)) {{
    stop(paste("Required package", pkg, "is not installed."))
  }}
}}

suppressPackageStartupMessages({{
  library(optparse)
  {LIBRARY_LOADS}
}})


# Define command line options
option_list <- list(
  {OPTIONS}
)

# Parse arguments
opt_parser <- OptionParser(
  usage = "%prog [options]",
  option_list = option_list,
  description = "{TOOL_NAME} wrapper for GenePattern"
)
opt <- parse_args(opt_parser)


# Validate inputs
validate_inputs <- function(opt) {{
  {VALIDATION}

  return(TRUE)
}}


# Run the tool
run_tool <- function(opt) {{
  tryCatch({{
    {EXECUTION}

    cat("Tool execution completed successfully\\n")
    return(TRUE)
  }}, error = function(e) {{
    cat(paste("Error:", e$message, "\\n"), file = stderr())
    return(FALSE)
  }})
}}


# Main execution
main <- function() {{
  # Validate inputs
  if (!validate_inputs(opt)) {{
    cat("Input validation failed\\n", file = stderr())
    quit(status = 1)
  }}

  # Run the tool
  success <- run_tool(opt)

  # Exit with appropriate status
  quit(status = if(success) 0 else 1)
}}

# Execute main function
main()

